# Generated by Django 4.2.10 on 2024-02-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductHub', '0002_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
