# Generated by Django 4.2.10 on 2024-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_user', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'subscription_details',
            },
        ),
    ]
